version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.local
    container_name: payment_Gateway_app
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on: 
      postgres:
        condition: service_started
    environment:
      - NODE_ENV=local
      - PORT=3000
      - DB_HOST=payment_Gateway_postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=orders
      - KAFKA_HOST=payment_Gateway_kafka:9094
      - KAFKA_CLIENT_ID=payment_gateway
      - KAFKA_USE_SSL=false
      - KAFKA_CONSUMER_GROUP_ID=payment_gateway
    networks:
      - payment_gateway_network

  postgres:
    image: postgres:14.7-alpine
    container_name: payment_Gateway_postgres
    ports:
      - 5432:5432
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    networks:
      - payment_gateway_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
 

networks:
  payment_gateway_network:
    external: true