version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.local
    container_name: payment_processor_app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=payment_Gateway_kafka:9094
    volumes:
      - .:/go/src


networks:
  payment_gateway_network:
    external: true