version: '3'

services:
  app:
    build: .
    container_name: Payment-Processor-app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=Payment-Processor-kafka:9092
    depends_on:
      kafka:
        condition: service_started
    volumes:
      - .:/go/src
    networks:
      - Payment-Processor-network
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: Payment-Processor-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - Payment-Processor-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: Payment-Processor-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: Payment-Processor-zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://Payment-Processor-kafka:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    networks:
      - Payment-Processor-network
    
  kafka-topics-generator:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    command: >
      bash -c
        "sleep 5s &&
        kafka-topics --create --topic=transactions --if-not-exists --bootstrap-server=Payment-Processor-kafka:9092 && 
        kafka-topics --create --topic=transactions_result --if-not-exists --bootstrap-server=Payment-Processor-kafka:9092"
    networks:
      - Payment-Processor-network

  control-center:
    image: confluentinc/cp-enterprise-control-center:6.0.1
    hostname: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'Payment-Processor-kafka:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      PORT: 9021
    networks:
      - Payment-Processor-network

networks:
  Payment-Processor-network:
    driver: bridge
