version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.local
    container_name: Payment-Processor-app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:9094
    volumes:
      - .:/go/src
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
