global:
  scrape_interval: "15s"
  evaluation_interval: "15s"


rule_files:

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['payment_processor_cadvisor:8080']
  - job_name: 'kakfa-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['payment_processor_kafka_exporter:9308']